# Generated by Django 5.1 on 2024-08-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project_delete_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='giturl',
            field=models.CharField(default='#', max_length=200),
        ),
    ]
